//! search.rs — 노래 추가용 통합 검색 (유튜브 영상 / 가사 사이트)
//!
//! 곡명·가수만 입력하면 URL을 직접 찾아 붙여넣지 않아도 되게 한다.
//!
//! * 유튜브: yt-dlp의 `ytsearch`로 목록을 받고(플랫 모드라 빠름), 상위 후보의
//!   설명만 병렬로 조회해 **공식 음원**을 판별한다. 유튜브 자동 생성 음원은
//!   설명이 "Provided to YouTube by …" / "Auto-generated by YouTube"로 시작하는데,
//!   이게 공식 음원을 가리키는 가장 확실한 신호라 이런 영상을 최상단에 올린다.
//!   (전체 메타데이터를 한 번에 받으면 5개에 10초 넘게 걸려 쓸 수 없다 —
//!   플랫 목록 2.5초 + 상위 몇 개 설명 병렬 조회 3초 수준으로 맞춤.)
//! * 가사: DuckDuckGo HTML 결과를 파싱해 가사 페이지 링크 후보를 준다
//!   (API 키가 필요 없음). 가사 원문은 저장하지 않고 링크만 다룬다.

use once_cell::sync::Lazy;
use regex::Regex;
use serde::Serialize;

use crate::youtube::YoutubeManager;

/// 설명 조회로 공식 음원 여부를 확인할 상위 후보 수. 각 조회가 ~2.5초라
/// 병렬로 돌려도 이 수가 커지면 체감이 나빠진다.
const OFFICIAL_PROBE_COUNT: usize = 6;

#[derive(Debug, Serialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct YoutubeSearchResult {
    pub id: String,
    pub url: String,
    pub title: String,
    pub channel: String,
    /// 초 단위. 알 수 없으면 0.
    pub duration: u64,
    pub thumbnail: String,
    /// 설명에 유튜브 자동 생성 음원 표식이 있는 영상(공식 음원).
    pub official: bool,
}

#[derive(Debug, Serialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct LyricsSearchResult {
    pub title: String,
    pub url: String,
    pub snippet: String,
    pub domain: String,
}

fn parse_flat_line(line: &str) -> Option<YoutubeSearchResult> {
    // yt-dlp --print "%(id)s|%(title)s|%(channel)s|%(duration)s"
    let mut parts = line.splitn(4, '|');
    let id = parts.next()?.trim().to_string();
    let title = parts.next()?.trim().to_string();
    let channel = parts.next().unwrap_or("").trim().to_string();
    let duration = parts
        .next()
        .unwrap_or("")
        .trim()
        .parse::<f64>()
        .map(|d| d as u64)
        .unwrap_or(0);
    if id.is_empty() || id == "NA" {
        return None;
    }
    Some(YoutubeSearchResult {
        url: format!("https://youtu.be/{}", id),
        thumbnail: format!("https://i.ytimg.com/vi/{}/mqdefault.jpg", id),
        id,
        title,
        channel,
        duration,
        official: false,
    })
}

/// 유튜브 검색 — 공식 음원(자동 생성 설명)을 최상단으로 올려 반환.
#[tauri::command]
pub async fn search_youtube(query: String, limit: Option<u32>) -> Result<Vec<YoutubeSearchResult>, String> {
    let q = query.trim().to_string();
    if q.is_empty() {
        return Ok(Vec::new());
    }
    let limit = limit.unwrap_or(8).clamp(1, 20);
    let exe = YoutubeManager::find_yt_dlp_public().await;

    let out = YoutubeManager::run_yt_dlp_capture(
        &exe,
        &[
            format!("ytsearch{}:{}", limit, q),
            "--flat-playlist".into(),
            "--no-warnings".into(),
            "--no-check-certificates".into(),
            "--print".into(),
            "%(id)s|%(title)s|%(channel)s|%(duration)s".into(),
        ],
    )
    .await?;

    let mut results: Vec<YoutubeSearchResult> =
        out.lines().filter_map(parse_flat_line).collect();

    // 상위 후보의 설명을 병렬로 받아 공식 음원 판별
    let probe = results.len().min(OFFICIAL_PROBE_COUNT);
    let mut handles = Vec::new();
    for r in results.iter().take(probe) {
        let exe = exe.clone();
        let url = r.url.clone();
        let id = r.id.clone();
        handles.push(tokio::spawn(async move {
            let desc = YoutubeManager::run_yt_dlp_capture(
                &exe,
                &[
                    url,
                    "--no-warnings".into(),
                    "--no-check-certificates".into(),
                    "--skip-download".into(),
                    "--print".into(),
                    "%(description)s".into(),
                ],
            )
            .await
            .unwrap_or_default();
            let head: String = desc.chars().take(400).collect();
            let official = head.contains("Provided to YouTube by")
                || head.contains("Auto-generated by YouTube");
            (id, official)
        }));
    }
    for h in handles {
        if let Ok((id, official)) = h.await {
            if official {
                if let Some(r) = results.iter_mut().find(|r| r.id == id) {
                    r.official = true;
                }
            }
        }
    }

    // 공식 음원 우선, 그 외에는 검색 순서 유지(안정 정렬)
    results.sort_by_key(|r| !r.official);
    Ok(results)
}

static DDG_RESULT_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r#"(?s)class="result__a"[^>]*href="([^"]+)"[^>]*>(.*?)</a>"#).unwrap()
});
static DDG_SNIPPET_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r#"(?s)class="result__snippet"[^>]*>(.*?)</a>"#).unwrap()
});
static TAG_RE: Lazy<Regex> = Lazy::new(|| Regex::new(r"<[^>]+>").unwrap());

fn strip_html(s: &str) -> String {
    let text = TAG_RE.replace_all(s, "");
    text.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#x27;", "'")
        .replace("&nbsp;", " ")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

/// DuckDuckGo 리다이렉트 링크(`//duckduckgo.com/l/?uddg=<encoded>&…`)에서 실제 URL 추출.
fn unwrap_ddg_url(href: &str) -> Option<String> {
    if let Some(idx) = href.find("uddg=") {
        let rest = &href[idx + 5..];
        let enc = rest.split('&').next().unwrap_or(rest);
        let decoded = urlencoding::decode(enc).ok()?.to_string();
        return Some(decoded);
    }
    if href.starts_with("http") {
        return Some(href.to_string());
    }
    None
}

fn domain_of(url: &str) -> String {
    url.split("://")
        .nth(1)
        .and_then(|rest| rest.split('/').next())
        .unwrap_or("")
        .trim_start_matches("www.")
        .to_string()
}

/// 가사 페이지 검색 — 곡명+가수로 웹 검색해 가사 사이트 링크 후보를 준다.
/// 가사 원문은 가져오지 않고 링크만 반환(저작권).
#[tauri::command]
pub async fn search_lyrics_sites(query: String) -> Result<Vec<LyricsSearchResult>, String> {
    let q = query.trim();
    if q.is_empty() {
        return Ok(Vec::new());
    }
    let search_q = format!("{} 가사", q);
    let client = reqwest::Client::builder()
        .user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36")
        .timeout(std::time::Duration::from_secs(15))
        .build()
        .map_err(|e| e.to_string())?;

    let body = client
        .get("https://html.duckduckgo.com/html/")
        .query(&[("q", search_q.as_str())])
        .send()
        .await
        .map_err(|e| format!("가사 검색 요청 실패: {}", e))?
        .text()
        .await
        .map_err(|e| format!("가사 검색 응답 읽기 실패: {}", e))?;

    let snippets: Vec<String> = DDG_SNIPPET_RE
        .captures_iter(&body)
        .map(|c| strip_html(&c[1]))
        .collect();

    let mut out = Vec::new();
    for (i, cap) in DDG_RESULT_RE.captures_iter(&body).enumerate() {
        let Some(url) = unwrap_ddg_url(&cap[1]) else { continue };
        let title = strip_html(&cap[2]);
        if title.is_empty() || url.is_empty() {
            continue;
        }
        out.push(LyricsSearchResult {
            domain: domain_of(&url),
            snippet: snippets.get(i).cloned().unwrap_or_default(),
            title,
            url,
        });
        if out.len() >= 8 {
            break;
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_flat_search_line() {
        let r = parse_flat_line("abc123|어떤 곡|어떤 채널|287").unwrap();
        assert_eq!(r.id, "abc123");
        assert_eq!(r.title, "어떤 곡");
        assert_eq!(r.channel, "어떤 채널");
        assert_eq!(r.duration, 287);
        assert_eq!(r.url, "https://youtu.be/abc123");
        assert!(r.thumbnail.contains("abc123"));
        assert!(!r.official);
    }

    #[test]
    fn flat_line_tolerates_missing_duration_and_pipes_in_title() {
        // 제목에 | 가 들어가도 채널/길이 자리를 침범하지 않도록 splitn(4) 사용 —
        // 다만 제목 안의 |는 남으므로(마지막 필드가 duration) NA는 0으로.
        let r = parse_flat_line("xyz|제목|채널|NA").unwrap();
        assert_eq!(r.duration, 0);
        assert!(parse_flat_line("NA|제목|채널|10").is_none());
    }

    #[test]
    fn unwraps_duckduckgo_redirect() {
        let href = "//duckduckgo.com/l/?uddg=https%3A%2F%2Fmusic.bugs.co.kr%2Ftrack%2F1804107&rut=abc";
        assert_eq!(
            unwrap_ddg_url(href).unwrap(),
            "https://music.bugs.co.kr/track/1804107"
        );
        assert_eq!(unwrap_ddg_url("https://example.com/x").unwrap(), "https://example.com/x");
        assert!(unwrap_ddg_url("/relative").is_none());
    }

    #[test]
    fn strips_html_and_reads_domain() {
        assert_eq!(strip_html("<b>가사</b> &amp; 노래"), "가사 & 노래");
        assert_eq!(domain_of("https://www.lyrics.co.kr/?p=1"), "lyrics.co.kr");
        assert_eq!(domain_of("https://music.bugs.co.kr/track/1"), "music.bugs.co.kr");
    }
}
